### ISSUE TITLE
References to absolute paths (C:/) found in code?

### ISSUE THREAD

**Issue by mithro** [lewiz-support/LMAC_CORE2#1]
The code has absolute paths in it, these are not great because;
 * Linux and Windows have different concepts of the best absolute path
 * Code needs to be at a given location to work correctly.

Here are some examples;
https://github.com/lewiz-support/LMAC_CORE2/blob/79507233b7e084b7c596035d053ee5277c638ba6/LMAC2_INFO/PHY_EMULATOR/phy_emulator_10G.v#L141-L142

**Comment by lewiz-support** [comment]
These paths are consistent with the project file and instructions provided with the core. This way the user does not need to change anything and can get up and running quickly.
We welcome contribution from the community for relative path version. Please provide appropriate instructions if you do make the changes.
